Provide sensible default tests for tests option
Fix Tox running Tox (complaining since local upgrade)

tox.exception.Error: Error: break infinite loop provisioning within /usr/bin/python3 missing ['tox>=3.20.0']